-- VISITS table
ALTER TABLE VISITS 
		ADD COLUMN COUNTRY_NAME VARCHAR (100) NULL,
		ADD COLUMN ISO2 CHAR (2) NULL,
		ADD COLUMN ID BIGING NOT NULL PRIMARY KEY;
		
		CREATE SEQUENCE SVISITS INCREMENT BY 1 START WITH 1 NO CYCLE OWNED BY VISITS.ID;