-- USER CREATION
CREATE USER linkindadmin WITH ENCRYPTED PASSWORD 'linkindadminpass';
ALTER USER linkindadmin NOCREATEDB;-- DB CREATION
CREATE DATABASE "linkind" ENCODING = 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE linkind TO linkindadmin;-- NOTICE: Below scripts should run on linkind schema
-- TABLES
CREATE TABLE USERS (
	ID BIGINT NOT NULL PRIMARY KEY,
	MAIL VARCHAR ( 60 ) NOT NULL,
	PASSWORD VARCHAR ( 128 ) NOT NULL,
	NICK_NAME VARCHAR ( 40 ) NOT NULL,
	CREATTION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ACTIVATION_DATE TIMESTAMP NULL,
	CONSTRAINT U_MAIL UNIQUE ( MAIL ) 
);
ALTER TABLE USERS ALTER COLUMN CREATTION_DATE 
SET DEFAULT CURRENT_TIMESTAMP;
CREATE TABLE LINKS (
	ID BIGINT NOT NULL PRIMARY KEY,
	URL VARCHAR ( 2000 ) NOT NULL,
	OWNER BIGINT NOT NULL,
	SHORT_URL VARCHAR ( 10 ) NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT U_SHORT_URL UNIQUE ( SHORT_URL ),
	CONSTRAINT F_OWNER FOREIGN KEY ( OWNER ) REFERENCES USERS ( ID ) 
);
ALTER TABLE LINKS ALTER COLUMN CREATION_DATE 
SET DEFAULT CURRENT_TIMESTAMP;
CREATE TABLE VISITS (
	ID BIGINT NOT NULL PRIMARY KEY,
	IP CHAR ( 19 ) NOT NULL,
	"DATE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LINK_ID BIGINT NOT NULL,
	BROWSER_NAME VARCHAR ( 50 ) NULL,
	BROWSER_VERSION VARCHAR ( 40 ) NULL,
	OS VARCHAR ( 30 ) NULL,
	COUNTRY_NAME VARCHAR (100) NULL,
	ISO2 CHAR (2) NULL,
	CONSTRAINT F_LINK FOREIGN KEY ( LINK_ID ) REFERENCES LINKS ( ID ) ON DELETE CASCADE 
);
CREATE TABLE TAGS (
	ID BIGINT NOT NULL PRIMARY KEY,
	NAME VARCHAR ( 100 ) NOT NULL,
	OWNER BIGINT NOT NULL,
	CONSTRAINT U_TAG UNIQUE ( NAME, OWNER ),
	CONSTRAINT F_TAG_OWNER FOREIGN KEY ( OWNER ) REFERENCES USERS ( ID ) ON DELETE CASCADE 
);
CREATE TABLE LINKSTAGS (
	LINK_ID BIGINT NOT NULL,
	TAG_ID BIGINT NOT NULL,
	CONSTRAINT F_TL_LINK FOREIGN KEY ( LINK_ID ) REFERENCES LINKS ( ID ) ON DELETE CASCADE,
	CONSTRAINT F_TL_TAG FOREIGN KEY ( TAG_ID ) REFERENCES TAGS ( ID ) ON DELETE CASCADE 
);
-- SEQUENCES
CREATE SEQUENCE SUSERS INCREMENT BY 1 START WITH 1 NO CYCLE OWNED BY USERS.ID;
CREATE SEQUENCE SLINKS INCREMENT BY 1 START WITH 1 NO CYCLE OWNED BY LINKS.ID;
CREATE SEQUENCE STAGS INCREMENT BY 1 START WITH 1 NO CYCLE OWNED BY TAGS.ID;
CREATE SEQUENCE SVISITS INCREMENT BY 1 START WITH 1 NO CYCLE OWNED BY VISITS.ID;

SELECT nextval('STAGS');