-- USER CREATION
CREATE USER linkindadmin WITH ENCRYPTED PASSWORD 'linkindadminpass';
ALTER USER linkindadmin NOCREATEDB;
-- DB CREATION
CREATE DATABASE "linkind" ENCODING = 'UTF8';
GRANT ALL PRIVILEGES ON DATABASE linkind TO linkindadmin;-- NOTICE: Below scripts should run on linkind schema
-- TABLES
CREATE TABLE USERS (
	ID BIGINT NOT NULL PRIMARY KEY,
	MAIL VARCHAR ( 60 ) NOT NULL,
	PASSWORD VARCHAR ( 128 ) NOT NULL,
	NICK_NAME VARCHAR ( 40 ) NOT NULL,
	CREATTION_DATE TIMESTAMP NOT NULL,
	ACTIVATION_DATE TIMESTAMP NULL,
	CONSTRAINT U_MAIL UNIQUE ( MAIL ) 
);
CREATE TABLE LINKS (
	ID BIGINT NOT NULL PRIMARY KEY,
	URL VARCHAR ( 2000 ) NOT NULL,
	OWNER BIGINT NOT NULL,
	SHORT_URL VARCHAR ( 10 ) NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	CONSTRAINT U_SHORT_URL UNIQUE ( SHORT_URL ),
	CONSTRAINT F_OWNER FOREIGN KEY ( OWNER ) REFERENCES USERS ( ID ) 
);-- SEQUENCES
CREATE SEQUENCE SUSERS INCREMENT BY 1 START WITH 1 NO CYCLE OWNED BY USERS.ID;
CREATE SEQUENCE SLINKS INCREMENT BY 1 START WITH 1 NO CYCLE OWNED BY LINKS.ID;